# Generated by Django 5.0.6 on 2024-05-22 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('genre_ids', models.CharField(max_length=255)),
                ('runtime', models.IntegerField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=255)),
                ('users_like', models.ManyToManyField(blank=True, related_name='movies_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='users_watched',
            field=models.ManyToManyField(blank=True, through='movieapp.WatchedMovie', to=settings.AUTH_USER_MODEL),
        ),
    ]
