# Generated by Django 5.0.12 on 2025-05-10 13:39

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
import movieapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tmdb_id', models.IntegerField()),
                ('is_Series', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('genre_ids', models.CharField(max_length=255)),
                ('episode_count', models.IntegerField(default=1)),
                ('runtime', models.IntegerField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(blank=True, max_length=255)),
                ('users_like', models.ManyToManyField(blank=True, related_name='movies_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=movieapp.models.avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateField(blank=True, default=None)),
                ('episodes_watched', models.IntegerField(default=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='users_watched',
            field=models.ManyToManyField(blank=True, through='movieapp.WatchedMovie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('tmdb_id', 'is_Series')},
        ),
    ]
