# Generated by Django 5.0.12 on 2025-05-10 16:00

from django.db import migrations

def create_profile(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('movieapp', 'Profile')  # Замените `yourapp` на имя вашего приложения
    
    for user in User.objects.all():
        # Проверяем, нет ли уже профиля у пользователя
        if not Profile.objects.filter(user=user).exists():
            Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile)
    ]

