# Generated by Django 5.0.12 on 2025-05-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedmovie',
            name='watched_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
